modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/PaintNinja/Presence-Footsteps-Forge"

[[mods]]
modId = "presencefootsteps"
version = "1.20.1-1.9.1-beta.1"
displayName = "Presence Footsteps (Forge)"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/presence-footsteps-forge"
updateJSONURL = "https://forge.curseupdate.com/433068/presencefootsteps"
authors = "Hurricaaane, Sollace, Paint_Ninja"
logoFile="presencefootsteps_logo.png"
description = "An overly complicated sound mod, ported to Forge."
displayTest="IGNORE_ALL_VERSION"

[[dependencies.presencefootsteps]]
modId = "forge"
mandatory = true
versionRange = "[47.2.19,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.presencefootsteps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"
